[package]
name = "chip8_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip8_cpu = { path = "../chip8_cpu" }
sdl2 = "0.35.2"
chrono = "0.4.31"
env_logger = "0.10.0"
log = "0.4.20"